# Generated by Django 5.1.2 on 2024-10-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cheqdet",
            fields=[
                (
                    "foliodet",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "movimiento",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
                ("comanda", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=14, null=True
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "impuesto1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "preciosinimpuestos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("tiempo", models.CharField(blank=True, max_length=20, null=True)),
                ("hora", models.DateTimeField(blank=True, null=True)),
                ("modificador", models.BooleanField(blank=True, null=True)),
                (
                    "mitad",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("comentario", models.CharField(blank=True, max_length=254, null=True)),
                ("idestacion", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "usuariodescuento",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "comentariodescuento",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "idtipodescuento",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("horaproduccion", models.DateTimeField(blank=True, null=True)),
                (
                    "idproductocompuesto",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "productocompuestoprincipal",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "preciocatalogo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("marcar", models.BooleanField(blank=True, null=True)),
                (
                    "idmeseroproducto",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "prioridadproduccion",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "estatuspatin",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("idcortesia", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "numerotarjeta",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "estadomonitor",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("llavemovto", models.CharField(blank=True, max_length=100, null=True)),
                ("horameserofinalizado", models.DateTimeField(blank=True, null=True)),
                (
                    "meserofinalizado",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("sistema_envio", models.IntegerField()),
                ("idturno_cierre", models.BigIntegerField(blank=True, null=True)),
                ("procesado", models.BooleanField(blank=True, null=True)),
                ("promovolumen", models.BooleanField()),
                ("iddispositivo", models.IntegerField()),
                ("productsyncidsr", models.IntegerField()),
                ("subtotalsrx", models.DecimalField(decimal_places=5, max_digits=7)),
                ("totalsrx", models.DecimalField(decimal_places=5, max_digits=7)),
                ("idmovtobillar", models.BigIntegerField()),
                ("idlistaprecio", models.IntegerField(blank=True, null=True)),
                (
                    "tipocambio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "impuestoimporte3",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "estrateca_discountcode",
                    models.CharField(db_column="estrateca_DiscountCode", max_length=50),
                ),
                (
                    "estrateca_discountid",
                    models.CharField(db_column="estrateca_DiscountID", max_length=50),
                ),
                (
                    "estrateca_discountamount",
                    models.DecimalField(
                        db_column="estrateca_DiscountAmount",
                        decimal_places=4,
                        max_digits=19,
                    ),
                ),
                (
                    "saledetailid",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "preciosinimpuestos_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "precio_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("escargoarea", models.BooleanField()),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de la venta",
                "verbose_name_plural": "Detalles de las ventas",
                "db_table": "cheqdet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cheques",
            fields=[
                ("folio", models.BigAutoField(primary_key=True, serialize=False)),
                ("seriefolio", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "numcheque",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                ("salidarepartidor", models.DateTimeField(blank=True, null=True)),
                ("arriborepartidor", models.DateTimeField(blank=True, null=True)),
                ("cierre", models.DateTimeField(blank=True, null=True)),
                ("mesa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nopersonas",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=3, null=True
                    ),
                ),
                ("idmesero", models.CharField(blank=True, max_length=4, null=True)),
                ("pagado", models.BooleanField(blank=True, null=True)),
                ("cancelado", models.BooleanField(blank=True, null=True)),
                ("impreso", models.BooleanField(blank=True, null=True)),
                (
                    "impresiones",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "cambio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "reabiertas",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "razoncancelado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "orden",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                ("facturado", models.BooleanField(blank=True, null=True)),
                ("idcliente", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "idarearestaurant",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("idempresa", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "tipodeservicio",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "idturno",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=6, null=True
                    ),
                ),
                (
                    "usuariocancelo",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "comentariodescuento",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("estacion", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "cambiorepartidor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "usuariodescuento",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("fechacancelado", models.DateTimeField(blank=True, null=True)),
                (
                    "idtipodescuento",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "numerotarjeta",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "folionotadeconsumo",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                ("notadeconsumo", models.BooleanField(blank=True, null=True)),
                ("propinapagada", models.BooleanField(blank=True, null=True)),
                (
                    "propinafoliomovtocaja",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                (
                    "puntosmonederogenerados",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "propinaincluida",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tarjetadescuento",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "porcentajefac",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=11, null=True
                    ),
                ),
                ("usuariopago", models.CharField(blank=True, max_length=15, null=True)),
                ("propinamanual", models.BooleanField(blank=True, null=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "idclientedomicilio",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("iddireccion", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "idclientefacturacion",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "telefonousadodomicilio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "totalarticulos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "subtotalsinimpuestos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalconpropina",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalimpuesto1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "cargo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalconcargo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalconpropinacargo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "descuentoimporte",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "efectivo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tarjeta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "vales",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "otros",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "propina",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "propinatarjeta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "campoadicional1",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "idreservacion",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "idcomisionista",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "importecomision",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("comisionpagada", models.BooleanField(blank=True, null=True)),
                ("fechapagocomision", models.DateTimeField(blank=True, null=True)),
                (
                    "foliopagocomision",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                (
                    "tipoventarapida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("callcenter", models.BooleanField(blank=True, null=True)),
                ("idordencompra", models.BigIntegerField(blank=True, null=True)),
                (
                    "totalsindescuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalalimentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalbebidas",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalotros",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totaldescuentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totaldescuentoalimentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totaldescuentobebidas",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totaldescuentootros",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalcortesias",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalcortesiaalimentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalcortesiabebidas",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalcortesiaotros",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totaldescuentoycortesia",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalalimentossindescuentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalbebidassindescuentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "totalotrossindescuentos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "descuentocriterio",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "descuentomonedero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "idmenucomedor",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "subtotalcondescuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "comisionpax",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("procesadointerfaz", models.BooleanField(blank=True, null=True)),
                ("domicilioprogramado", models.BooleanField(blank=True, null=True)),
                (
                    "fechadomicilioprogramado",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("enviado", models.BooleanField(blank=True, null=True)),
                ("ncf", models.CharField(blank=True, max_length=19, null=True)),
                (
                    "numerocuenta",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "codigo_unico_af",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("estatushub", models.IntegerField(blank=True, null=True)),
                (
                    "idfoliohub",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                (
                    "enviadorw",
                    models.BooleanField(blank=True, db_column="EnviadoRW", null=True),
                ),
                ("usuarioapertura", models.CharField(max_length=15)),
                (
                    "titulartarjetamonedero",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "saldoanteriormonedero",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "autorizacionfolio",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("fechalimiteemision", models.DateTimeField(blank=True, null=True)),
                (
                    "totalimpuestod1",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "totalimpuestod2",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "totalimpuestod3",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "idmotivocancela",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sistema_envio", models.IntegerField()),
                (
                    "idformadepagodescuento",
                    models.CharField(db_column="idformadepagoDescuento", max_length=5),
                ),
                ("titulartarjetamonederodescuento", models.CharField(max_length=100)),
                ("foliotempcheques", models.BigIntegerField(blank=True, null=True)),
                ("c_iddispositivo", models.IntegerField()),
                ("salerestaurantid", models.TextField()),
                ("timemarktoconfirmed", models.DateTimeField(blank=True, null=True)),
                ("timemarktodelivery", models.DateTimeField(blank=True, null=True)),
                (
                    "timemarktodeliveryarrive",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("esalestatus", models.IntegerField()),
                ("statussr", models.IntegerField(db_column="statusSR")),
                ("paymentreference", models.CharField(max_length=50)),
                (
                    "deliverycharge",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("comandaimpresa", models.BooleanField(blank=True, null=True)),
                ("foodorder", models.IntegerField()),
                (
                    "cashpaymentwith",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("paymentmethod_id", models.IntegerField()),
                ("surveycode", models.CharField(max_length=18)),
                ("intentoenvioaf", models.IntegerField(db_column="intentoEnvioAF")),
                ("tkc_token", models.CharField(db_column="TKC_Token", max_length=50)),
                (
                    "tkc_transaction",
                    models.CharField(db_column="TKC_Transaction", max_length=100),
                ),
                (
                    "tkc_authorization",
                    models.CharField(db_column="TKC_Authorization", max_length=100),
                ),
                ("tkc_cupon", models.CharField(db_column="TKC_Cupon", max_length=100)),
                (
                    "tkc_expirationdate",
                    models.CharField(db_column="TKC_ExpirationDate", max_length=100),
                ),
                (
                    "tkc_recompensa",
                    models.DecimalField(
                        db_column="TKC_Recompensa", decimal_places=4, max_digits=19
                    ),
                ),
                ("campoadicional2", models.CharField(max_length=250)),
                ("campoadicional3", models.CharField(max_length=250)),
                (
                    "estrateca_cardnumber",
                    models.CharField(db_column="estrateca_CardNumber", max_length=100),
                ),
                (
                    "estrateca_vouchertext",
                    models.TextField(db_column="estrateca_VoucherText"),
                ),
                ("campoadicional4", models.CharField(max_length=250)),
                ("campoadicional5", models.CharField(max_length=250)),
                (
                    "sacoa_cardnumber",
                    models.CharField(db_column="sacoa_CardNumber", max_length=100),
                ),
                ("sacoa_credits", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "estrateca_typedisccount",
                    models.CharField(
                        db_column="estrateca_TypeDisccount", max_length=50
                    ),
                ),
                (
                    "estrateca_discountcode",
                    models.CharField(db_column="estrateca_DiscountCode", max_length=50),
                ),
                (
                    "estrateca_discountid",
                    models.CharField(db_column="estrateca_DiscountID", max_length=50),
                ),
                (
                    "estrateca_discountamount",
                    models.DecimalField(
                        db_column="estrateca_DiscountAmount",
                        decimal_places=4,
                        max_digits=19,
                    ),
                ),
                (
                    "desc_imp_original",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("donativo", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "totalcondonativo",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "totalconpropinacargodonativo",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("orderreference", models.CharField(max_length=500)),
                ("appname", models.CharField(max_length=250)),
                ("paymentproviderid", models.CharField(max_length=50)),
                ("paymentprovider", models.CharField(max_length=250)),
                (
                    "changestatussrx",
                    models.BooleanField(
                        blank=True, db_column="ChangeStatusSRX", null=True
                    ),
                ),
                (
                    "datedownload",
                    models.DateTimeField(
                        blank=True, db_column="DateDownload", null=True
                    ),
                ),
                ("comandaimpresacancelada", models.BooleanField(blank=True, null=True)),
                ("empaquetado", models.DateTimeField(blank=True, null=True)),
                ("status_domicilio", models.IntegerField()),
                ("asignacion", models.DateTimeField(blank=True, null=True)),
                ("enviopagado", models.BooleanField()),
                ("diet_restrictions", models.CharField(max_length=250)),
                ("sl_cupon_descuento", models.CharField(max_length=250)),
                ("sl_tipo_cupon", models.CharField(max_length=50)),
                (
                    "sl_importe_descuento",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tuki_cardnumber",
                    models.CharField(db_column="TUKI_CardNumber", max_length=250),
                ),
                (
                    "tuki_accumulatedpoints",
                    models.DecimalField(
                        blank=True,
                        db_column="TUKI_AccumulatedPoints",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "tuki_currentpoints",
                    models.DecimalField(
                        blank=True,
                        db_column="TUKI_CurrentPoints",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "sl_num_cupones",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=16, null=True
                    ),
                ),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
                ("sentsync", models.BooleanField(db_column="SentSync")),
                (
                    "subtotal_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "total_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "totalconpropinacargo_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("mv_room", models.CharField(max_length=100)),
                ("mv_lastname", models.CharField(max_length=100)),
                ("estado", models.BooleanField(blank=True, null=True)),
                (
                    "totalsindescuentoimp",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "cheques",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chequespagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.BigIntegerField()),
                (
                    "importe",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "propina",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tipodecambio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("referencia", models.TextField(blank=True, null=True)),
                ("idturno_cierre", models.BigIntegerField(blank=True, null=True)),
                ("procesado", models.BooleanField(blank=True, null=True)),
                ("sistema_envio", models.IntegerField()),
                (
                    "importe_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "propina_ec",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "workspaceid",
                    models.CharField(db_column="WorkspaceId", max_length=36),
                ),
                ("cardbrand", models.CharField(db_column="cardBrand", max_length=120)),
                (
                    "importe_cashdro",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen venta",
                "verbose_name_plural": "Resumen de ventas",
                "db_table": "chequespagos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Empresas",
            fields=[
                (
                    "idempresa",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "razonsocial",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=250, null=True)),
                ("sucursal", models.CharField(blank=True, max_length=250, null=True)),
                ("rfc", models.CharField(blank=True, max_length=150, null=True)),
                ("curp", models.CharField(blank=True, max_length=150, null=True)),
                ("telefono", models.CharField(blank=True, max_length=150, null=True)),
                ("giro", models.CharField(blank=True, max_length=200, null=True)),
                ("contacto", models.CharField(blank=True, max_length=200, null=True)),
                ("fax", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.CharField(blank=True, max_length=250, null=True)),
                ("fechacompra", models.DateTimeField(blank=True, null=True)),
                (
                    "distribuidor",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "numerofactura",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "numerodecontrol",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contrasenacontrol",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("idhardware", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "licenciaprincipal",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciamonederoelectronico",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciamonitorproduccion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciasrmovil",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciamanttoventas",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciapagoenlinea",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciahuelladigital",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "licenciabillar",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("franquicia", models.BooleanField(blank=True, null=True)),
                ("web", models.CharField(blank=True, max_length=200, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=150, null=True)),
                ("estado", models.CharField(blank=True, max_length=150, null=True)),
                ("pais", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "ciudadsucursal",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "estadosucursal",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "passwordempresa",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("escedis", models.BooleanField(blank=True, null=True)),
                ("idproveedor", models.CharField(blank=True, max_length=15, null=True)),
                ("escorporativo", models.BooleanField(blank=True, null=True)),
                (
                    "codigopostal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("ventapedidocedis", models.BooleanField(blank=True, null=True)),
                (
                    "descuentocedis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "claveunicaempresa",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("regimen", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "idempresahub",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "logohub",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("logoempresa", models.TextField()),
                ("logoempresaext", models.CharField(max_length=10)),
                ("prefijoempresa", models.CharField(max_length=3)),
                (
                    "a86ed5f9d02ec5b3",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("idplaza", models.CharField(blank=True, max_length=15, null=True)),
                ("idcompania", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "idubicacionempresa",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "idzonaempresa",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("asientos", models.IntegerField(blank=True, null=True)),
                (
                    "metroscuadrados",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "fechaapertura",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fechacierre", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "fechamodificado",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("imagen_logo_menu", models.TextField(blank=True, null=True)),
                ("imagen_portada_menu", models.TextField(blank=True, null=True)),
                ("eslogan", models.CharField(max_length=300)),
                ("nombre_menu", models.CharField(max_length=300)),
                ("codigopostalsucursal", models.CharField(max_length=100)),
                (
                    "idregimen_sat",
                    models.CharField(db_column="idregimen_SAT", max_length=50),
                ),
                ("uid", models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Estados",
            fields=[
                (
                    "idestado",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "estados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Formasdepago",
            fields=[
                (
                    "idformadepago",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "tipo",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "tipodecambio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("solicitareferencia", models.BooleanField(blank=True, null=True)),
                (
                    "prioridadboton",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
                (
                    "cuentacontableimporte",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "cuentacontablecomision",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "cuentacontableivacomision",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "comision",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("visible", models.BooleanField(blank=True, null=True)),
                ("aceptapropina", models.BooleanField(blank=True, null=True)),
                ("subtipo", models.SmallIntegerField(blank=True, null=True)),
                ("prefijo1", models.CharField(blank=True, max_length=3, null=True)),
                ("prefijo2", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "codigodeprefijoconsulta",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "codigodeprefijoacumred",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("generapuntos", models.BooleanField(blank=True, null=True)),
                (
                    "formatoimpresion",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
                (
                    "idfpagofiscal",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "pagoenlinea",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "tipotarjeta",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("imagen", models.BinaryField(blank=True, max_length="max", null=True)),
                ("nofacturable", models.BooleanField(blank=True, null=True)),
                (
                    "comisionreporte1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "comisionreporte2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tipotarjetabancaria",
                    models.SmallIntegerField(db_column="tipoTarjetaBancaria"),
                ),
                ("idtipodescuento", models.CharField(max_length=5)),
                (
                    "idformapago_sat",
                    models.CharField(db_column="idformapago_SAT", max_length=50),
                ),
                ("leerbrazalete", models.BooleanField()),
                ("cargohabitacion_eg", models.BooleanField()),
                ("visible_kiosco", models.BooleanField()),
                ("autocapturar", models.BooleanField()),
                ("sumatotal", models.BooleanField()),
                (
                    "equivalencia",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de pago",
                "verbose_name_plural": "Formas de pago",
                "db_table": "formasdepago",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupos",
            fields=[
                (
                    "idgrupo",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "clasificacion",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "prioridad",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                (
                    "color",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "colorletra",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "prioridadimpresion",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("cambiacolorcuenta", models.BooleanField(blank=True, null=True)),
                (
                    "colorcuenta",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "colorletracuenta",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("solicitaautorizacion", models.BooleanField(blank=True, null=True)),
                (
                    "imagenmenuelectronico",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("extmenu", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "porcentajepropina",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("imagen_menu", models.TextField(blank=True, null=True)),
                ("id_etiqueta", models.CharField(max_length=50)),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
                ("alcohol", models.BooleanField()),
                ("idbo", models.IntegerField(blank=True, db_column="IdBO", null=True)),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "db_table": "grupos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Paises",
            fields=[
                (
                    "idpais",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Pais",
                "verbose_name_plural": "Paises",
                "db_table": "paises",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "idproducto",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
                ("nombrecorto", models.CharField(blank=True, max_length=20, null=True)),
                ("plu", models.CharField(blank=True, max_length=30, null=True)),
                ("imagen", models.BinaryField(blank=True, max_length="max", null=True)),
                ("nofacturable", models.BooleanField(blank=True, null=True)),
                ("comentario", models.CharField(blank=True, max_length=254, null=True)),
                ("usarcomedor", models.BooleanField(blank=True, null=True)),
                ("usardomicilio", models.BooleanField(blank=True, null=True)),
                ("usarrapido", models.BooleanField(blank=True, null=True)),
                ("usarcedis", models.BooleanField(blank=True, null=True)),
                (
                    "idinsumospresentaciones",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "imagenmenuelectronico",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                (
                    "descripcionmenuelectronico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("usarmenuelectronico", models.BooleanField(blank=True, null=True)),
                ("extmenu", models.CharField(blank=True, max_length=5, null=True)),
                ("imagen_menu", models.TextField(blank=True, null=True)),
                ("descripcion_detalle", models.CharField(max_length=300)),
                ("calorias", models.DecimalField(decimal_places=0, max_digits=18)),
                ("visible_menu", models.BooleanField()),
                ("capturar_pendientes", models.BooleanField()),
                ("id_etiqueta", models.CharField(max_length=50)),
                ("id_etiqueta_descripcion", models.CharField(max_length=50)),
                (
                    "idprodserv_sat",
                    models.CharField(db_column="idprodserv_SAT", max_length=50),
                ),
                ("usarvectorplus", models.BooleanField(db_column="usarVectorPlus")),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
                ("imagenme_modified", models.BooleanField()),
                (
                    "imagenbackoffice",
                    models.BinaryField(blank=True, max_length="max", null=True),
                ),
                ("monitoreo", models.BooleanField()),
                (
                    "prioridadimpresion",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=4, null=True
                    ),
                ),
                ("idbo", models.IntegerField(blank=True, db_column="IdBO", null=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Regionempresa",
            fields=[
                (
                    "idregionempresa",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Region de la Empresa",
                "verbose_name_plural": "Regiones de la Empresa",
                "db_table": "regionempresa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Servicecodes",
            fields=[
                (
                    "servicecode",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("sistema", models.SmallIntegerField()),
                ("tipo", models.SmallIntegerField()),
            ],
            options={
                "verbose_name": "Codigo de Servicio",
                "verbose_name_plural": "Codigos de Servicios",
                "db_table": "servicecodes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tipoempresa",
            fields=[
                (
                    "idtipoempresa",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Empresa",
                "verbose_name_plural": "Tipos de Empresas",
                "db_table": "tipoempresa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Udsmedida",
            fields=[
                (
                    "idunidad",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "idunidadmedida_sat",
                    models.CharField(db_column="idunidadmedida_SAT", max_length=50),
                ),
                (
                    "workspaceid",
                    models.CharField(
                        blank=True, db_column="WorkspaceId", max_length=36, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de Medida",
                "verbose_name_plural": "Unidades de Medida",
                "db_table": "udsmedida",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Productosdetalle",
            fields=[
                (
                    "idproducto",
                    models.ForeignKey(
                        blank=True,
                        db_column="idproducto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="mantventas_api.productos",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "impuesto1",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "impuesto3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "preciosinimpuestos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("bloqueado", models.BooleanField(blank=True, null=True)),
                (
                    "precioabierto",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("canjeablepuntos", models.BooleanField(blank=True, null=True)),
                (
                    "preciopuntos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "puntoscanje",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "puntosextras",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("lunesinicio", models.CharField(blank=True, max_length=11, null=True)),
                ("lunesfin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "preciolunes",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "lunesdiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "martesinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("martesfin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "preciomartes",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "martesdiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "miercolesinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "miercolesfin",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "preciomiercoles",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "miercolesdiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "juevesinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("juevesfin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "preciojueves",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "juevesdiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "viernesinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("viernesfin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "precioviernes",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "viernesdiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "sabadoinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("sabadofin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "preciosabado",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "sabadodiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                (
                    "domingoinicio",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("domingofin", models.CharField(blank=True, max_length=11, null=True)),
                (
                    "preciodomingo",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "domingodiasalida",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("aplicalunes", models.BooleanField(blank=True, null=True)),
                ("aplicamartes", models.BooleanField(blank=True, null=True)),
                ("aplicamiercoles", models.BooleanField(blank=True, null=True)),
                ("aplicajueves", models.BooleanField(blank=True, null=True)),
                ("aplicaviernes", models.BooleanField(blank=True, null=True)),
                ("aplicasabado", models.BooleanField(blank=True, null=True)),
                ("aplicadomingo", models.BooleanField(blank=True, null=True)),
                ("excentoimpuestos", models.BooleanField(blank=True, null=True)),
                ("secuenciacompuesto", models.BooleanField(blank=True, null=True)),
                (
                    "finalizarsecuenciacompuesto",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "heredarmonitormodificadores",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "comisionvendedor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("eliminarfiscal", models.BooleanField(blank=True, null=True)),
                (
                    "enviarproduccionsimodificador",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "cargoadicional",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=5, null=True
                    ),
                ),
                ("afectacomensales", models.BooleanField(blank=True, null=True)),
                (
                    "comensalesafectados",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=2, null=True
                    ),
                ),
                ("descargar", models.BooleanField(blank=True, null=True)),
                (
                    "usarmultiplicadorprodcomp",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "rentabilidadcedis",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("idarea", models.CharField(blank=True, max_length=4, null=True)),
                ("permitirprodcompenmodif", models.BooleanField(blank=True, null=True)),
                (
                    "politicapuntos",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=1, null=True
                    ),
                ),
                ("favorito", models.BooleanField(blank=True, null=True)),
                ("ocultarmitades", models.BooleanField()),
                ("dev_impuestoimporte3", models.BooleanField()),
                (
                    "impuestoimporte3",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("usa_imagen_monitor", models.BooleanField()),
                ("rutaimagen", models.TextField(blank=True, null=True)),
                (
                    "comisionprecio",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("usa_bascula", models.BooleanField()),
            ],
            options={
                "verbose_name": "Detalle de producto",
                "verbose_name_plural": "Detalles de productos",
                "db_table": "productosdetalle",
                "managed": False,
            },
        ),
    ]
